import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import localFont from 'next/font/local'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const PlayfairDisplay = localFont({
  src: './fonts/PlayfairDisplay-ExtraBold.ttf'
})
const PlayfairDisplayItallic = localFont({
  src: './fonts/PlayfairDisplay-Italic.ttf'
})
export {PlayfairDisplay , PlayfairDisplayItallic}
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` bg-yellow-50 ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
